### ISSUE TITLE
Checklist for bundling

### ISSUE THREAD

**Issue by nikic** [jedisct1/libsodium-php#117]
A random collection of TODOs (not everything has to necessarily happen before we bundle):

 * [ ] @jedisct1 should request a PHP account and commit karma (at least for ext/sodium, maybe general)
 * [ ] IIRC the plan was to drop sodium_hex2bin and sodium_bin2hex in favor of hex2bin() and bin2hex(). However, the PHP implementations should be made timing-safe first.
 * [x] The big reindent. php-src uses tabs, while this repo uses spaces.
 * [ ] I think for this library it would be good to switch to zend_parse_parameters_throw, such that invalid arguments result in an exception rather than a warning.
 * [ ] A number of functions seem to have incorrect arginfo. Would be good to review this and make sure eveything is correct.
 * [ ] General API review. After this is released in 7.2 it will be very hard to change existing function signatures, so any changes should happen now.

Anything else missing?

**Comment by jedisct1** [comment]
I got a PHP account for the PECL extension. Do I need another one?

**Comment by nikic** [comment]
@jedisct1 Not totally sure, but it does look like the PECL account should work. In that case we only have to make sure you get the necessary commit karma.

**Comment by paragonie-scott** [comment]
Do we want to make `sodium_crypto_*` abbreviate to `sodium_*` in PHP-land?

**Comment by fredemmott** [comment]
> IIRC the plan was to drop sodium_hex2bin and sodium_bin2hex in favor of hex2bin() and bin2hex(). However, the PHP implementations should be made timing-safe first.

I don't feel strongly here, though for reference, it's been discussed before on php-internals; I think it's happened a few times, but can only find:

http://grokbase.com/t/php/php-internals/14bs5tmqbr/php-src-constant-time-bin2hex-implementation-909

That said, changing them is in the sodium RFC :) https://wiki.php.net/rfc/libsodium
